myshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'), name='index'),
]

shop/urls.py
from django.urls import path
from .views import user, seller, login, shops, computers, trolley, brand

app_name = 'shop'  #声明namespace

urlpatterns = [
    path('', user.index, name='index'),
    path('login/', login.login, name='login'),
    path('register/', login.register, name='register'),
    path('logout/', login.logout, name='logout'),
    path('user/index/<int:user_id>/', user.userIndex, name='userIndex'),
    path('seller/index/<int:seller_id>/', seller.sellerIndex, name='sellerIndex'),
    path('shops/', shops.shops, name='shops'),
    path('computers/', computers.computers, name='computers'),
    path('computers/details/<str:computer_id>/', computers.details, name='computerDetail'),
    path('shops/details/<int:shop_id>/', shops.details, name='shopDetail'),
    path('trolley/<int:user_id>/', trolley.trolley, name='trolley'),
    path('buy/trolley/<int:user_id>/', trolley.buy, name='trolley_buy'),
    path('add/trolley/<str:sell_id>/<int:user_id>/', trolley.add, name='trolley_add'),
    path('delete/trolley/<int:trolley_id>/', trolley.delete, name='trolley_delete'),
    path('brand/detail/<str:name>/', brand.brand, name='brand'),
    path('recharge/<int:user_id>', user.recharge, name='recharge'),
    path('coupon/get/<int:user_id>/', user.getCoupon, name='getCoupon'),
    path('coupon/delete/<int:coupon_id>/', user.deleteCoupon, name='deleteCoupon'),
    path('buy/record/<int:user_id>/', user.buyRecord, name='buyRecord'),
    path('computers/details/post/<int:user_id>/<str:computer_id>/', computers.post, name='postComputerComment'),
    path('seller/openshop/<int:seller_id>/', seller.openShop, name='openShop'),
    path('seller/record/<int:seller_id>/', seller.sellRecord, name='sellerRecord'),
    path('shop/record/<int:shop_id>/', shops.sellRecord, name='shopSellRecord'),
    path('shop/details/post/<int:user_id>/<int:shop_id>/', shops.post, name='postShopComment'),
    path('shop/manage/<int:shop_id>/', shops.manage, name='shopManage'),
    path('shop/manage/computer/<int:shop_id>/<str:computer_id>/', shops.computerManage, name='shopComputerManage'),
    path('shop/add/<int:shop_id>/computer/<str:computer_id>/', shops.computerAdd, name='shopComputerAdd'),
    path('shop/delete/<int:shop_id>/computer/<str:computer_id>/', shops.computerDelete, name='shopComputerDelete'),
    path('computers/detail/<str:computer_id>/mark/<int:user_id>/', computers.makeMark, name='mark'),
    path('brand/like/<str:name>/<int:user_id>/', brand.makeLike, name='like'),
    path('all/brand/', brand.allBrands, name='allBrands'),
]

shop/views/brand.py
from shop.models import *
from django.shortcuts import *
from django.db.models import Sum
from django.core.exceptions import ObjectDoesNotExist

def brand(request, name):
	rtx = {}
	rtx['isUser'] = request.session.get('type', '') == 'user'
	rtx['user_id'] = request.session.get('id', '')

	rtx['brand'] = Brand.objects.get(pk=name)
	rtx['turnover'] = Buy.objects.filter(computer_id__brand=rtx['brand']).aggregate(Sum('price'))[r'price__sum']
	rtx['likeNumber'] = like.objects.filter(brand_name=rtx['brand']).count()
	rtx['followers'] = like.objects.filter(brand_name=rtx['brand'])

	rtx['like'] = '取消关注' if like.objects.filter(brand_name__name=name, user_id__user_id=rtx['user_id']).count() > 0 else '关注'

	rtx['computers'] = []
	for c in Computer.objects.filter(brand__name=name):
		rtx['computers'].append((c.computer_id, c.cpu, c.memory, Buy.objects.filter(computer_id__brand__name=name).count()))

	rtx['net'] = rtx['brand'].net
	if rtx['net'][:4] != 'http':
		rtx['net'] = 'http://' + rtx['net']

	return render(request, 'Dashio/brand.html', rtx)

def makeLike(request, name, user_id):
  try:
    m = like.objects.get(brand_name__name=name, user_id__user_id=user_id)
    m.delete()
  except ObjectDoesNotExist:
    brand = get_object_or_404(Brand, pk=name)
    user = get_object_or_404(User, pk=user_id)
    like(brand_name=brand, user_id=user).save()
  
  return HttpResponseRedirect(reverse('shop:brand', args=(name, )))

def allBrands(request):
	brands = Brand.objects.all()
	rtx = {'brands': []}
	for b in brands:
		rtx['brands'].append([b.name, b.country, b.found_date, Computer.objects.filter(brand=b).count(), Buy.objects.filter(computer_id__brand=b).aggregate(Sum('price'))[r'price__sum']])
		if rtx['brands'][-1][4] is None:
			rtx['brands'][-1][4] = 0.0
	
	if request.method == 'POST':
		sortKey = {'name': 0, 'country': 1, 'found_date': 2, 'computerNumber': 3, 'turnover': 4}
		rtx['brands'].sort(key=lambda x: x[sortKey[request.POST['sort']]], reverse=(request.POST['sortType'] == '-'))
	
	return render(request, 'Dashio/allbrand.html', rtx)

shop/views/computers.py
from django.shortcuts import *
from shop.models import *
from django.db import transaction
from django.core.exceptions import *

@transaction.atomic
def computers(request):
  ctx = {}
  computer = Computer.objects.all()
  ctx['brand'] = Brand.objects.all()

  if request.method == 'POST':
    if request.POST['computer_id'] != '':
      computer = computer.filter(computer_id__icontains=request.POST['computer_id'])
    if request.POST['cpu'] != '':
      computer = computer.filter(cpu__icontains=request.POST['cpu'])
    if request.POST['graphics_card'] != '':
      computer = computer.filter(graphics_card__icontains=request.POST['graphics_card'])
    
    try:
      if request.POST['minMemory'] != '':
        computer = computer.filter(memory__gte=int(request.POST['minMemory']))
      if request.POST['maxMemory'] != '':
        computer = computer.exclude(memory__gte=int(request.POST['maxMemory']))

      if request.POST['minssd'] != '':
        computer = computer.filter(ssd_capacity__gte=int(request.POST['minssd']))
      if request.POST['maxssd'] != '':
        computer = computer.exclude(ssd_capacity__gte=int(request.POST['maxssd']))

      if request.POST['minDisk'] != '':
        computer = computer.filter(disk_capacity__gte=int(request.POST['minDisk']))
      if request.POST['maxDisk'] != '':
        computer = computer.exclude(disk_capacity__gte=int(request.POST['maxDisk']))

    except ValueError:
      return render(request, 'Dashio/error.html', {'error': "请输入整数"})
    
    if request.POST.get('brand', '') != '':
      print(request.POST['brand'])
      computer = computer.filter(brand__name__icontains=request.POST['brand'])

    if request.POST['sort'] != '':
      sortKey = request.POST['sortType'] + request.POST['sort']
      computer = computer.order_by(sortKey)

  ctx['computer'] = computer
  return render(request, "Dashio/computers.html", ctx)

@transaction.atomic
def details(request, computer_id):
  rtx = {}
  rtx['isUser'] = request.session['type'] == 'user'
  rtx['computer'] = get_object_or_404(Computer, pk=computer_id)
  rtx['markAmount'] = mark.objects.filter(computer_id__computer_id=computer_id).count()
  rtx['sell'] = Sell.objects.filter(computer_id__computer_id=computer_id)
  rtx['user_id'] = request.session['id']
  rtx['sellAmount'] = Buy.objects.filter(computer_id__computer_id=computer_id).count()
  rtx['comments'] = computer_comment.objects.filter(computer_id__computer_id=computer_id).order_by('-comment_date')
  rtx['buys'] = Buy.objects.filter(computer_id__computer_id=computer_id).order_by('-buy_time')[:5]
  
  if rtx['isUser']:
    rtx['mark'] = ('收藏' if mark.objects.filter(user_id__user_id=rtx['user_id'], computer_id=rtx['computer']).count() == 0 else '取消收藏')

  return render(request, 'Dashio/computer_detail.html', rtx)

@transaction.atomic
def post(request, user_id, computer_id):
  if request.method == 'POST':
    computer = Computer.objects.get(pk=computer_id)
    user = User.objects.get(pk=user_id)
    computer_comment(computer_id=computer, user_id=user, content=request.POST['comment']).save()
  
  return HttpResponseRedirect(reverse('shop:computerDetail', args=(computer_id, )))

def makeMark(request, computer_id, user_id):
  try:
    m = mark.objects.get(computer_id__computer_id=computer_id, user_id__user_id=user_id)
    m.delete()
  except ObjectDoesNotExist:
    computer = get_object_or_404(Computer, pk=computer_id)
    user = get_object_or_404(User, pk=user_id)
    mark(computer_id=computer, user_id=user).save()
  
  return HttpResponseRedirect(reverse('shop:computerDetail', args=(computer_id, )))

shop/views/index.py
from django.shortcuts import *
from shop.models import *
from django.db import transaction
from django.utils.timezone import now, timedelta

def index(request):
	user_id, type_ = request.session.get('id', None), request.session.get('type', None)
	if user_id is None:
		return HttpResponseRedirect(reverse('shop:login'))
	elif type_ == 'user':
		return HttpResponseRedirect(reverse('shop:userIndex', args=(user_id,)))
	elif type_ == 'seller':
		return HttpResponseRedirect(reverse('shop:sellerIndex', args=(user_id,)))

def userIndex(request, user_id):
	rt = {}
	if request.session.get('id', None) == user_id and request.session.get('type') == 'user':
		rt['curUser'] = True
	else: rt['curUser'] = False

	curUser = User.objects.get(user_id=user_id)
	rt['user_id'] = curUser.user_id
	rt['user_name'] = curUser.name
	rt['balance'] = curUser.balance

	rt['coupon'] = Coupon.objects.filter(owner__user_id=user_id)
	rt['buy'] = Buy.objects.filter(user_id__user_id=user_id)
	rt['mark'] = mark.objects.filter(user_id__user_id=user_id)
	rt['trolley'] = shopping_cart.objects.filter(user_id__user_id=user_id)

	return render(request, 'shop/userProfile.html', rt)

@transaction.atomic
def recharge(request, user_id):
	if not (request.session.get('id', None) == user_id and request.session.get('type', None) == 'user'):
		return render(request, 'shop/error.html', {'error': '你不能为他人充值'})
	
	if request.method == 'GET':
		return render(request, 'shop/recharge.html', {'user_id': user_id})
	elif request.method == 'POST':
		if request.POST['value'] == '':
			return render(request, 'shop/error.html', {'error': '请输入一个数值'})
		
		value = int(request.POST['value'])
		curUser = User.objects.get(user_id=user_id)
		curUser.balance += value
		curUser.save()

		return render(request, 'shop/notice.html', {'notice': '您已成功充值'+str(value)+'元'})

@transaction.atomic
def getCoupon(request, user_id):
	if not (request.session.get('id', None) == user_id and request.session.get('type', None) == 'user'):
		return render(request, 'shop/error.html', {'error': '你不能为他人领取代金券'})
	
	if request.method == 'GET':
		return render(request, 'shop/getCoupon.html', {'user_id': user_id})
	elif request.method == 'POST':
		if request.POST.get('value', '') == '':
			if request.POST['userDefinedValue'] == '':
				return render(request, 'shop/error.html', {'error': '请输入一个数值'})
			else: value = int(request.POST['userDefinedValue'])
		else: value = int(request.POST['value'])

		curUser = User.objects.get(user_id=user_id)
		Coupon(value=value, owner=curUser, expired= now().date()+timedelta(days=7)).save()

		return render(request, 'shop/notice.html', {'notice': '您已成功领取'+str(value)+'元代金券'})

def deleteCoupon(request, coupon_id):
	Coupon(coupon_id=coupon_id).delete()
	return HttpResponseRedirect(reverse('shop:index'))

def sellerIndex(request, seller_id):
	curUser = User.objects.get(user_id=seller_id)
	return render(request, 'shop/profile.html', {'name':curUser.name})

shop/views/login.py
from django.http import HttpResponse, Http404
from django.shortcuts import *
from shop.models import *
from django.db import transaction

import hashlib

def md5Encode(s):
  m = hashlib.md5()
  m.update(s.encode(encoding='utf-8'))
  return m.hexdigest()

@transaction.atomic
def login(request):
	rt = {'error_message': ''}
	if request.method == 'GET':
		return render(request, 'Dashio/login.html', rt)
		
	elif request.method == 'POST':
		if request.POST['type'] == 'user':
			try:
				user_id = int(request.POST['user_id'])
				psw = request.POST['psw']
			except ValueError:
				rt['error_message'] = '账号不存在'
				return render(request, 'Dashio/login.html', rt)

			q = User.objects.filter(user_id=user_id)
			if not q.exists():
				rt['error_message'] = '账号不存在'
				return render(request, 'Dashio/login.html', rt)
			
			if md5Encode(str(psw)) != q[0].password:
				rt['error_message'] = '密码错误'
				return render(request, 'Dashio/login.html', rt)
			
			request.session['id'], request.session['type'] = user_id, 'user'
			return HttpResponseRedirect(reverse('shop:userIndex', args=(user_id, )))

		elif request.POST['type'] == 'seller':
			try:
				seller_id = int(request.POST['user_id'])
				psw = request.POST['psw']
			except ValueError:
				rt['error_message'] = '账号不存在'
				return render(request, 'Dashio/login.html', rt)

			q = Seller.objects.filter(seller_id=seller_id)
			if not q.exists():
				rt['error_message'] = '账号不存在'
				return render(request, 'Dashio/login.html', rt)
			
			if md5Encode(str(psw)) != q[0].password:
				rt['error_message'] = '密码错误'
				return render(request, 'Dashio/login.html', rt)

			request.session['id'], request.session['type'] = seller_id, 'seller'
			return HttpResponseRedirect(reverse('shop:sellerIndex', args=(seller_id, )))

@transaction.atomic
def register(request):
	rt = {'error_message': ''}
	if request.method == 'GET':
		return render(request, 'Dashio/register.html', rt)
	elif request.method == 'POST':
		user_name = request.POST['user_name']
		psw = request.POST['psw']
		psw_confirm = request.POST['psw_confirm']
		address = request.POST['address']
		sex = request.POST['sex']
		type_ = request.POST['type']

		if not user_name: rt['error_message'] = '用户名不能为空'
		if not psw: rt['error_message'] = '密码不能为空'
		if not address: rt['error_message'] = '地址不能为空'
		if psw != psw_confirm: rt['error_message'] = '两次输入密码不一致'

		if rt['error_message']:
			return render(request, 'Dashio/register.html', rt)
		
		if type_ == 'user':
			new_user = User(name=user_name, password=md5Encode(str(psw)), sex=sex, address=address)
			new_user.save()
			request.session['id'], request.session['type'] = new_user.user_id, 'user'
			return HttpResponseRedirect(reverse('shop:userIndex', args=(new_user.user_id,)))
		elif type_ == 'seller':
			new_seller = Seller(name=user_name, password=md5Encode(str(psw)))
			new_seller.save()
			request.session['id'], request.session['type'] = new_seller.seller_id, 'seller'
			return HttpResponseRedirect(reverse('shop:sellerIndex', args=(new_seller.seller_id, )))

def logout(request):
	request.session['id'], request.session['type'] = None, None
	return HttpResponseRedirect(reverse('shop:login'))

shop/views/trolley.py
from django.shortcuts import *
from shop.models import *
from django.db import transaction
import datetime

@transaction.atomic
def trolley(request, user_id):
	if not (request.session.get('id', None) == user_id and request.session.get('type', None) == 'user'):
		return HttpResponse("Sorry, 你不能操作他人的购物车")
	
	trolley = shopping_cart.objects.filter(user_id__user_id=user_id)
	if not trolley.exists():
		return render(request, "Dashio/notice.html", {'notice': "你的购物车空空如也"})
		
	coupon = Coupon.objects.filter(owner__user_id=user_id, expired__gte=datetime.datetime.now())

	# rt['trolley'][i][0] = computer_id, rt['trolley'][i][1] = shop_id, rt['trolley'][i][2] = shop_name, rt['trolley'][i][3] = price, rt['trolley'][i][4] = shopping_cart.id
	rt = {'trolley': trolley, 'coupon': coupon, 'name': User.objects.get(user_id=user_id).name, 'total': 0.0, 'couponTotal': 0.0, 'user_id': user_id}

	for t in trolley:
		rt['total'] += t.sell.price
	for c in coupon:
		rt['couponTotal'] += c.value
	rt['total'] -= rt['couponTotal']
	if rt['total'] < 0: rt['total'] = 0.0
	
	return render(request, 'Dashio/trolley.html', rt)

@transaction.atomic
def buy(request, user_id):
	# 清空购物车，清空优惠券，添加订单，改变余额
	trolley = shopping_cart.objects.filter(user_id__user_id=user_id)
	curUser = User.objects.get(user_id=user_id)
	coupon = Coupon.objects.filter(owner__user_id=user_id, expired__gte=datetime.datetime.now())
	
	total, couponTotal = 0.0, 0.0
	for t in trolley:
		total += t.sell.price
	for c in coupon:
		couponTotal += c.value
	total -= couponTotal
	if total < 0: total = 0.0

	if total > curUser.balance:
		return render(request, 'Dashio/error.html', {'error': '您的余额不足'})
	
	for c in trolley:
		Buy(computer_id=c.sell.computer_id, shop_id=c.sell.shop_id, user_id=c.user_id, price=c.sell.price).save()
		seller = Seller.objects.get(seller_id=c.sell.shop_id.seller.seller_id)
		seller.balance += c.sell.price
		seller.save()

	trolley.delete()
	coupon.delete()
	curUser.balance -= total
	curUser.save()
	return render(request, 'Dashio/notice.html', {'notice': '购买成功，谢谢惠顾!'})

@transaction.atomic
def add(request, sell_id, user_id):
	curUser = User.objects.get(user_id=user_id)
	sell = get_object_or_404(Sell, pk=sell_id)
	shopping_cart(sell=sell, user_id=curUser).save()
	return render(request, 'Dashio/addTrolley.html', {'user_id': user_id, 'computer_id': sell.computer_id.computer_id})

@transaction.atomic
def delete(request, trolley_id):
	trolley = shopping_cart.objects.get(id=trolley_id)
	user_id = trolley.user_id.user_id
	trolley.delete()
	return HttpResponseRedirect(reverse('shop:trolley', args=(user_id, )))

templates/Dashio/customer.html
<!DOCTYPE html>
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Online Shop</title>

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png'%}" rel="icon">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <!--external css-->
  <link href="{% static 'lib/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_page.css'%}" rel="stylesheet" />
  <link href="{% static 'lib/advanced-datatable/css/demo_table.css'%}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'lib/advanced-datatable/css/DT_bootstrap.css'%}" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css'%}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css'%}" rel="stylesheet">

  <!-- =======================================================
    Template Name: Dashio
    Template URL: https://templatemag.com/dashio-bootstrap-admin-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>
  <section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
      <div class="sidebar-toggle-box">
        <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
      </div>
      <!--logo start-->
      <a href="{% url 'shop:index' %}" class="logo"><b>COM<span>PUTER</span></b></a>
      <!--logo end-->
      <div class="nav notify-row" id="top_menu">
        <!--  notification start -->
        <ul class="nav top-menu">
          
          
      </div>
      <div class="top-menu">
        <ul class="nav pull-right top-menu">
          <li><a class="logout" href="{% url 'shop:logout' %}">Logout</a></li>
        </ul>
      </div>
    </header>
    <!--header end-->
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
          <li class="mt">
            <a href="{% url 'shop:index' %}">
              <i class="fa fa-user"></i>
              <span>个人空间</span>
              </a>
          </li>
          <li class="mt">
            <a href="{% url 'shop:computers' %}">
              <i class="fa fa-desktop"></i>
              <span>所有电脑</span>
              </a>
          </li>
          <li class="mt">
            <a href="{% url 'shop:shops' %}">
              <i class="fa fa-building-o"></i>
              <span>所有店铺</span>
              </a>
          </li>
          <li class="mt">
            <a href="{% url 'shop:allBrands' %}">
              <i class="fa fa-male"></i>
              <span>所有品牌</span>
              </a>
          </li>
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <h3><i class="fa fa-angle-right"></i> {{user_name}}(id:{{user_id}}, user_type:{{user_type}})</h3>
        <p>账户余额:{{balance}}&nbsp&nbsp<a href="{% url 'shop:recharge' user_id %}"> <button type="button" class="btn btn-primary btn-xs">账户充值</button> </a>
</p>
        <div class="row">
          <div class="col-md-12">
            <div class="content-panel">
              <h4><i class="fa fa-angle-right"></i> 购买记录&nbsp&nbsp</h4>
              <hr>
              <table class="table">
                <thead>
                  <tr>
                    <th><i class="fa fa-desktop"></i>型号</th>
                    <th><i class=" fa fa-shopping-cart">店铺</th>
                    <th><i class="fa fa-money"></i>价格</th>
                    <th><i class="fa fa-clock-o"></i>日期</th>
                  </tr>
                </thead>
                <tbody>
                {% for record in buy %}
                  <tr>
                    <td><a href="{% url 'shop:computerDetail' record.computer_id.computer_id %}">{{record.computer_id.computer_id}} </a></td>
                    <td><a href="{% url 'shop:shopDetail' record.shop_id.shop_id %}">{{record.shop_id.name}} </a></td>
                    <td>{{record.price}}元</td>
                    <td>{{record.buy_time}}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
             <br>
             <a href="{% url 'shop:buyRecord' user_id %}"><button type="button" class="btn btn-success">查看更多</button></a>
          </div>
          <!-- /col-md-12 -->
          <div class="col-md-12 mt">
            <div class="content-panel">
              <table class="table table-hover">
                <h4><i class="fa fa-angle-right"></i> 当前购物车&nbsp&nbsp</h4>
                <hr>
                <thead>
                  <tr>
                    <th><i class="fa fa-desktop">型号</th>
                    <th><i class="fa fa-shopping-cart">店铺</th>
                    <th><i class="fa fa-money"></i>价格</th>
                  </tr>
                </thead>
                <tbody>
                {% for record in trolley %}
                  <tr>
                    <td><a href="{% url 'shop:computerDetail' record.sell.computer_id.computer_id %}">{{record.sell.computer_id.computer_id}} </a></td>
                    <td><a href="{% url 'shop:shopDetail' record.sell.shop_id.shop_id %}">{{record.sell.shop_id.name}} </a></td>
                    <td>{{record.sell.price}}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
               {% if curUser %}<br><a href="{% url 'shop:trolley' user_id %}"> <button type="button" class="btn btn-primary">去结算</button> </a>{% endif %} 
          </div>
          <!-- /col-md-12 -->
          <div class="col-md-12 mt">
            <div class="content-panel">
              <table class="table table-hover">
                <h4><i class="fa fa-angle-right"></i> 代金券&nbsp&nbsp</h4>
                <hr>
                <thead>
                  <tr>
                    <th><i class=" fa fa-money">面值</th>
                    <th><i class="fa fa-clock-o"></i>过期日期</th>
                    {% if curUser %}<th> 操作 </th>{% endif %}
                  </tr>
                </thead>
                <tbody>
                {% for record in coupon %}
                  <tr>
                    <td>{{record.value}}元</td>
                    <td>{{record.expired}}</td>
                    {% if curUser %}<td> <a href="{% url 'shop:deleteCoupon' record.coupon_id %}"><button type="button" class="btn btn-danger btn-xs">删除</button></a> </td>{% endif %}
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <br>
            {% if curUser %}
            <a href="{% url 'shop:getCoupon' user_id %}"> <button type="button" class="btn btn-primary">领取代金券</button> </a>
            {% endif %}
          </div>
          <!-- /col-md-12 -->
        </div>
        <!-- row -->
        <div class="row mt">
          <div class="col-md-12">
            <div class="content-panel">
              <table class="table table-striped table-advance table-hover">
                <h4><i class="fa fa-angle-right"></i> 收藏夹</h4>
                <hr>
                <thead>
                  <tr>
                    <th><i class="fa fa-desktop"></i>型号</th>
                    <th><i class="fa fa-clock-o"></i>收藏日期</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {% for record in mark %}
                    <td><a href="{% url 'shop:computerDetail' record.computer_id.computer_id %}">{{record.computer_id.computer_id}} </a></td>
                    <td>{{record.date}}</td>
                  </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /content-panel -->
          </div>
          <!-- /col-md-12 -->
        </div>
        <!-- /row -->
      </section>
    </section>
    <!-- /MAIN CONTENT -->
    <!--main content end-->

  </section>
  <!-- js placed at the end of the document so the pages load faster -->
  <script src="{% static 'lib/jquery/jquery.min.js'%}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js'%}"></script>
  <script class="include" type="text/javascript" src="{% static 'lib/jquery.dcjqaccordion.2.7.js'%}"></script>
  <script src="{% static 'lib/jquery.scrollTo.min.js'%}"></script>
  <script src="{% static 'lib/jquery.nicescroll.js'%}" type="text/javascript"></script>
  <!--common script for all pages-->
  <script src="{% static 'lib/common-scripts.js'%}"></script>
  <!--script for this page-->
  
</body>

</html>